### ISSUE TITLE
Sibelia error: Input is larger than 1 GB, can't proceed

### ISSUE THREAD

**Issue by dnarnapr** [bioinf/Sibelia#185]
When using Sibelia, I encountered this error : Input is larger than 1 GB, can't proceed. My genomic data is large, over 2G.  How can I solve this problem?

**Comment by ilyaminkin** [comment]
Hi @dnarnapr,

Sibelia does not support large inputs. We will release the new version of Sibelia in January, it will support very large datasets, like tens of mammalian genomes. In the meanwhile, you can try something like https://github.com/glennhickey/progressiveCactus, it should work for 2 GB just fine.

**Comment by dnarnapr** [comment]
Thank you very much for your reply.

**Comment by iminkin** [comment]
SibeliaZ allows for building synteny blocks for large genomes resembling functionality of the original Sibelia: https://github.com/medvedevgroup/SibeliaZ#building-synteny-blocks

**Comment by MdUmar-tech** [comment]
Sir, I am having contig of novel bacterial genome at genus level, how should I use Cibelia, I mean do I have to make single fasta file or concatenated file how will I rearanged them or should I cant use contig file, because whatever available genome in NCBI is all are in contigue form, minimum 10 genome I am doing for sibelia software is it ok 
please share the script also
thanks
